<?php

/**
 * @file
 * Contains commerce_vendor.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_vendor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_vendor module.
    case 'help.page.commerce_vendor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Vendor content entity for commerce module') . '</p>';
      return $output;

    default:
  }
}
