<?php

/**
 * @file
 * Profile form mode.
 */

/**
 * Implements hook_entity_type_alter().
 */
function profile_form_mode_entity_type_alter(array &$entity_types) {
  $formModeOptions = \Drupal::service('entity_display.repository')->getFormModeOptions('profile');
  foreach ($formModeOptions as $formMode => $formModeLabel) {
    if ($formMode != 'default') {
      $entity_types['profile']->setFormClass($formMode, 'Drupal\profile\Form\ProfileForm');
    }
  }
}
