<?php

/**
 * @file
 * This module extends link attributes.
 */

/**
 * Implements template_preprocess_field().
 */
function advance_link_attributes_preprocess_field(&$variables) {
  if ($variables['field_type'] == 'link') {
    $element = $variables['element'];
    foreach ($element['#items'] as $delta => $item) {
      if (!empty($element[$delta]['#options']['parent_classes'])) {
        $variables['items'][$delta]['attributes']->setAttribute('class', $element[$delta]['#options']['parent_classes']);
      }
    }
  }
}
