<?php

/**
 * @file
 * Provides default AGERP Core Basic entities and the ability to create more.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function agerp_core_basic_theme() {
  return [
    'agerp_core_party' => [
      'render element' => 'elements',
      'template' => 'agerp-core-party',
    ],
    'agerp_core_resource' => [
      'render element' => 'elements',
      'template' => 'agerp-core-resource',
    ],
  ];
}


/**
 * Process variables for AGERP Core Party.
 *
 * Default template: agerp-core-party.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - agerp_core_party: The AGERP Core Party entity.
 */
function template_preprocess_agerp_core_party(array &$variables) {
  agerp_core_basic_common_template_preprocess('agerp_core_party', $variables);
}


/**
 * Common theme template additions.
 *
 * @param string $entity_id
 *   Entity.
 * @param array $variables
 *   Variables.
 */
function agerp_core_basic_common_template_preprocess(string $entity_id, array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  /** @var \Drupal\Core\Entity\EntityInterface $entity */
  $entity = $variables['elements']['#' . $entity_id];
  $variables['agerp_core_basic'] = $entity;

  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  // Add classes based on the type of contact.
  $variables['attributes']['class'][] = $entity_id;
  $variables['attributes']['class'][] = $entity_id. '-' . $entity->bundle();
}


/**
 * Implements hook_theme_suggestions_HOOK().
 */
function agerp_core_basic_theme_suggestions_agerp_core_party(array $variables) {
  return agerp_core_basic_theme_suggestions_common(
    'agerp_core_party',
    $variables['elements']['#agerp_core_party'],
    $variables['elements']['#view_mode']
  );
}

/**
 * Common suggestions for resources and parties.
 *
 * @param string $entity_id
 *   Entity.
 * @param \Drupal\agerp_core_basic\PartyInterface|\Drupal\agerp_core_basic\ResourceInterface $entity
 *   Entity.
 *
 * @return array
 */
function agerp_core_basic_theme_suggestions_common(string $entity_id, $entity, string $view_mode): array {
  $suggestions = [];
  $sanitized_view_mode = strtr($view_mode, '.', '_');

  // Add template suggestions.
  $suggestions[] = $entity_id . '__' . $sanitized_view_mode;
  $suggestions[] = $entity_id . '__' . $entity->bundle();
  $suggestions[] = $entity_id . '__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = $entity_id . '__' . $entity->id();
  $suggestions[] = $entity_id . '__' . $entity->id() . '__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Implements hook_mail().
 */
function agerp_core_basic_mail($key, &$message, $params) {
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['message'];
}
