<?php

/**
 * @file
 * Contains modal_block.module.
 */

/**
 * Implements hook_theme().
 */
function modal_block_theme($existing, $type, $theme, $path) {
  return [
    'modal_block' => [
      'variables' => [
        'content' => [],
        'attributes' => [],
        'settings' => [],
        'modal_block_id' => '',
      ],
    ],
    'block__modal_block' => [
      'base hook' => 'block',
    ],
  ];
}



