<?php

/**
 * @file
 * Banana Dashboard.
 * @TODO: icons should be swapable + some other approach then classes
 * @TODO: create example yaml
 */

/**
 * Implements hook_theme().
 */
function banana_dashboard_theme($existing, $type, $theme, $path) {
  return [
        'banana_dashboard' => [
            'variables' => ['title' => '', 'dashboard_menu' => '']
        ]
  ];
}

/**
 * Get one config value.
 *
 * @param string $name
 *   The key or title.
 * @param null $default_value
 *   Default value.
 *
 * @return mixed|null
 *   Returns data.
 */
function banana_dashboard_get($name, $default_value = NULL) {
  $data = banana_dashboard_load_config();
  return isset($data[$name]) ? $data[$name] : $default_value;
}

/**
 * Load config from plugin manager.
 */
function banana_dashboard_load_config() {
  $data = \Drupal::service('plugin.manager.banana_dashboard')->getDefinitions();
  return $data;
}

/**
 * Legacy icon map to fontawesome.
 */
function _banana_dashboard_legacy_icon_map() {
  return [
    "file" => "file-o",
    "bars" => "bars",
    "pen" => "pencil",
    "hammer" => "gear",
    "menu" => "bars",
    "profile" => "user-o",
    "users" => "users",
    "bookmarks" => "bookmark",
    "numbered-list" => "list",
  ];
}
