<?php

/**
* @file
* Procedural hooks for the Views Inc. Rewrite URL module
*/

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views_pretty_path\PathProcessor\ViewsPrettyPathProcessor;


/**
 * Implements hook_help().
 */
function views_pretty_path_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'views_pretty_path.views_pretty_path_admin_form':
      $output = '';
      $output .= '<p>' . t('Use this page to configure the paths and associated views for which URLs should be rewritten into a more user- and SEO-friendly format.') .
      ' <a href="' . \Drupal::request()->getSchemeAndHttpHost() . '/admin/help/views_pretty_path">See help.</a></p>';
      return $output;
      break;
    case 'help.page.views_pretty_path':
        $output = '';
        $output .= '<p>' . t('Use Views Pretty Path to configure the paths and associated views for which URLs should be rewritten into a more user- and SEO-friendly format.') . '</p>';
        $output .= '<p>' . t('For example, this module would take this URL:.') . '</p>';
        $output .= '<pre>http://example.com/blog?keys=blockchain&field_topic_target_id%5B54%5D=54&field_asset_type_target_id%5B14%5D=14</pre>';
        $output .= '<p>' . t('And rewrite it as:') . '</p>';
        $output .= '<pre>http://example.com/blog/filter/assets/article/topics/technology/keywords/blockchain.</pre>';
        return $output;
        break;
  }
}


/**
 * Implements hook_preprocess_pager()
 */
function views_pretty_path_preprocess_pager(&$variables) {
  /** @var ViewsPrettyPathProcessor $views_rewrite_preprocessor */
  $views_rewrite_preprocessor = \Drupal::service('views_pretty_path.path_processor');
  $views_rewrite_preprocessor->preProcessPager($variables);
}

/**
 * Implements hook_form_views_exposed_form_alter()
 */
function views_pretty_path_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = '_views_pretty_path_views_exposed_form_submit_handler';
}

/**
 * Custom submit handler for views exposed forms
 *
 * @param array $form
 * @param FormStateInterface $form_state
 */
function _views_pretty_path_views_exposed_form_submit_handler(&$form, FormStateInterface $form_state) {
  /** @var ViewsPrettyPathProcessor $views_rewrite_preprocessor */
  $views_rewrite_preprocessor = \Drupal::service('views_pretty_path.path_processor');
  $views_rewrite_preprocessor->handleViewsExposedFormSubmit($form, $form_state);
}

/**
 * Implements hook_view_predelete()
 */
function views_pretty_path_view_predelete(EntityInterface $view) {
  // Delete config associated w/ view, if any.
  $config = \Drupal::service('config.factory')->getEditable('views_pretty_path.config');
  $paths = $config->get('paths');
  foreach ($paths as $key => $path_value) {
    if ($view->id() == $path_value['view']) {
      unset($paths[$key]);
      $config->set('paths', $paths);
      $config->save();
      break;
    }
  }
}
