<?php

/**
 * @file
 * Primary module hooks for Group Behavior module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\group_behavior\GroupBehaviorEntityHooks;
use Drupal\group_behavior\GroupBehaviorFormHooks;

/**
 * Implements hook_form_FORM_ID_alter() for group_type_edit_form.
 */
function group_behavior_form_group_type_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  GroupBehaviorFormHooks::alterGroupTypeEditForm($form, $form_state, $form_id);
}

/**
 * Implements hook_entity_insert().
 */
function group_behavior_entity_insert(EntityInterface $entity) {
  GroupBehaviorEntityHooks::insert($entity);
}

/**
 * Implements hook_entity_update().
 */
function group_behavior_entity_update(EntityInterface $entity) {
  GroupBehaviorEntityHooks::update($entity);
}

/**
 * Implements hook_entity_delete().
 */
function group_behavior_entity_delete(EntityInterface $entity) {
  GroupBehaviorEntityHooks::delete($entity);
}

/**
 * Implements hook_entity_translation_insert().
 */
function group_behavior_entity_translation_insert(EntityInterface $translation) {
  GroupBehaviorEntityHooks::insertTranslation($translation);
}

/**
 * Implements hook_entity_translation_delete().
 */
function group_behavior_entity_translation_delete(EntityInterface $translation) {
  GroupBehaviorEntityHooks::deleteTranslation($translation);
}

/**
 * Implements hook_module_implements_alter().
 */
function group_behavior_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'entity_delete') {
    // We remove the group_delete implementation here and call it in our hook.
    // @see \Drupal\group_behavior\EntityHooks::delete
    unset($implementations['group']);
  }
}
