<?php

/**
 * @file
 * Contains nbox.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function nbox_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nbox module.
    case 'help.page.nbox':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The nbox module provides an full fledged internal mail/messaging system.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_element_info_alter().
 */
function nbox_element_info_alter(array &$types) {
  // Attach our extra CSS for toolbar icons.
  if (isset($types['toolbar'])) {
    $types['toolbar']['#attached']['library'][] = 'nbox/toolbar';
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function nbox_nbox_metadata_update(EntityInterface $entity) {
  /** @var \Drupal\nbox\Entity\NboxMetadata $entity */
  $deleteStatus = $entity->getDeleteStatus();
  // If the delete status changes, check if thread & messages can be deleted.
  if ($deleteStatus !== $entity->original->getDeleteStatus()) {
    $entity->deleteWithCheck();
  }
}
