<?php

/**
 * @file
 * Contains react_calendar.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function react_calendar_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the react_calendar module.
    case 'help.page.react_calendar':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('React frontend for the Drupal 8 Calendar module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function react_calendar_theme() {
  return [
    'react_calendar' => [
      'variables' => [
        'data_source' => NULL,
        'default_view' => NULL,
        'language_prefix' => NULL,
        'language_id' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}
