<?php

/**
 * @file
 * Controls the visual building blocks, views a page is constructed with.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function clever_theme_switcher_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.clever_theme_switcher':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module allows you to switch topics for different conditions.') . '</p>';
      $output .= '<p>' . t('For more information, see the <a href="https://www.drupal.org/project/clever_theme_switcher">Clever Theme Switcher</a>.') . '</p>';
      $output .= '<br>';
      $output .= '<h3>' . t('Usage') . '</h3>';
      $output .= '<p>' . t('The module is integrated with several default plugins.') . '</p>';
      $output .= '<p>' . t('But if this is not enough, you can write your own plugin and register it.') . '</p>';
      $output .= '<p>' . t('After registering the plugin, you can use it as a condition for displaying the topic.') . '</p>';
      $output .= '<br>';
      $output .= '<h6>' . t('First step') . '</h6>';
      $output .= '<p>' . t('You must create your <b>ConditionPlugin</b> plugin. This plugin can have any logic.') . '</p>';
      $output .= '<p>' . t('In any case, it will return either the TRUE or the FALSE.') . '</p>';
      $output .= '<h6>' . t('Second step') . '</h6>';
      $output .= '<p>' . t('Create your EventSubscriber and register your plugin in it. $request->attributes->set("_cts_plugin_handler",[]);') . '</p>';
      return $output;
  }
}
