<?php

/**
 * @file
 * Contains redhen_asset.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\redhen_asset\Entity\AssetType;

/**
 * Denotes that the asset is not active.
 */
const REDHEN_ASSET_INACTIVE = 0;

/**
 * Denotes that the asset is active.
 */
const REDHEN_ASSET_ACTIVE = 1;

/**
 * Implements hook_help().
 */
function redhen_asset_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the redhen_asset module.
    case 'help.page.redhen_asset':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Defines the base asset entity and features.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function redhen_asset_theme() {
  $theme = [];
  $theme['redhen_asset'] = [
    'render element' => 'elements',
    'file' => 'redhen_asset.page.inc',
    'template' => 'redhen_asset',
  ];
  $theme['redhen_asset_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'redhen_asset.page.inc',
  ];
  return $theme;
}

/**
 * Return an associative array of asset types to be used as an options list.
 *
 * @return array
 *   Keyed by name with a label value.
 */
function redhen_asset_type_options_list() {
  $options = array();
  foreach (AssetType::loadMultiple() as $type) {
    $options[$type->id()] = $type->label();
  }

  return $options;
}

/**
 * Implements hook_tokens().
 */
function redhen_asset_tokens($type, $tokens, array $data, array $options, \Drupal\Core\Render\BubbleableMetadata $bubbleable_metadata) {
  $replacements = array();

  if (($type == 'entity') && isset($data['entity_type']) && ($data['entity_type'] == 'redhen_asset')) {

    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'id':
          $replacements[$original] = $data['entity']->id();
          break;
      }
    }

  }

  return $replacements;
}

/**
 * Implements hook_token_info().
 */
function redhen_asset_token_info() {
  $type = array(
    'name' => t('Asset'),
    'description' => t('Tokens related to an individual Assets.'),
    'needs-data' => 'redhen_asset',
  );

  $redhen_asset['id'] = array(
    'name' => t('Asset ID'),
    'description' => t('The unique ID of the Asset.'),
  );

  return array(
    'types' => array('redhen_asset' => $type),
    'tokens' => array('redhen_asset' => $redhen_asset),
  );
}
