<?php

/**
 * @file
 * Contains resource.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\resource\ResourceInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function resource_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the resource module.
    case 'help.page.resource':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides resource entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function resource_theme() {
  $theme = [
    'resource' => array(
      'render element' => 'elements',
    ),
    'resource_add_list' => array(
      'variables' => array('content' => NULL),
    ),
  ];

  return $theme;
}

/**
 * Prepares variables for Resource templates.
 *
 * Default template: resource.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_resource(array &$variables) {
  // Fetch Resource Entity Object.
  $resource = $variables['elements']['#resource'];

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for list of available resource type templates.
 *
 * Default template: resource-add-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: An array of content types.
 *
 * @see resource_add_page()
 */
function template_preprocess_resource_add_list(array &$variables) {
  $variables['types'] = array();
  if (!empty($variables['content'])) {
    foreach ($variables['content'] as $type) {
      $variables['types'][$type->id()] = array(
        'type' => $type->id(),
        'add_link' => \Drupal::l($type->label(), new Url('resource.add', array('resource_type' => $type->id()))),
      );
    }
  }
}

/**
 * Implements hook_resource_access().
 */
function resource_resource_access(ResourceInterface $resource, $op, $account) {
  $type = $resource->bundle();
  switch ($op) {
    case 'view':
      if ($account->hasPermission('view any ' . $type . ' resource entities', $account)) {
        return AccessResult::allowed()->cachePerPermissions();
      }
      else {
        return AccessResult::allowedIf($account->hasPermission('view own ' . $type . ' resource entities', $account) && ($account->id() == $resource->getOwnerId()))->cachePerPermissions()->cachePerUser()->cacheUntilEntityChanges($resource);
      }

    case 'update':
      if ($account->hasPermission('edit any ' . $type . ' resource entities', $account)) {
        return AccessResult::allowed()->cachePerPermissions();
      }
      else {
        return AccessResult::allowedIf($account->hasPermission('edit own ' . $type . ' resource entities', $account) && ($account->id() == $resource->getOwnerId()))->cachePerPermissions()->cachePerUser()->cacheUntilEntityChanges($resource);
      }

    case 'delete':
      if ($account->hasPermission('delete any ' . $type . ' resource entities', $account)) {
        return AccessResult::allowed()->cachePerPermissions();
      }
      else {
        return AccessResult::allowedIf($account->hasPermission('delete own ' . $type . ' resource entities', $account) && ($account->id() == $resource->getOwnerId()))->cachePerPermissions()->cachePerUser()->cacheUntilEntityChanges($resource);
      }

    default:
      // No opinion.
      return AccessResult::neutral();
  }
}

/**
 * Implements hook_resource_create_access().
 */
function resource_resource_create_access(AccountInterface $account, array $context, $entity_bundle = NULL) {
  return AccessResult::allowedIfHasPermission($account, 'create ' . $entity_bundle . ' resource entities')->cachePerPermissions();
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alters the theme form to use the admin theme on resource editing.
 *
 * @see resource_form_system_themes_admin_form_submit()
 */
function resource_form_system_themes_admin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['admin_theme']['resource_use_admin_theme'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use the administration theme when editing or creating resource entity'),
    '#default_value' => \Drupal::configFactory()->getEditable('resource.settings')->get('resource_use_admin_theme'),
  );
  $form['#submit'][] = 'resource_form_system_themes_admin_form_submit';
}

/**
 * Form submission handler for system_themes_admin_form().
 *
 * @see resource_form_system_themes_admin_form_alter()
 */
function resource_form_system_themes_admin_form_submit($form, FormStateInterface $form_state) {
  \Drupal::configFactory()->getEditable('resource.settings')
    ->set('resource_use_admin_theme', $form_state->getValue('resource_use_admin_theme'))
    ->save();
  \Drupal::service('router.builder')->setRebuildNeeded();
}
