<?php

/**
 * @file
 * Provides a demo store for Commerce.
 */

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function commerce_demo_theme($existing, $type, $theme, $path) {
  return [
    'commerce_demo_frontpage' => [
      'variables' => [
        'featured_products' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_menu_links_discovered_alter().
 *
 * Workaround for taxonomy_menu not supporting custom paths. See #2865894.
 */
function commerce_demo_menu_links_discovered_alter(&$links) {
  $alias_cleaner = \Drupal::service('pathauto.alias_cleaner');
  $facet_storage = \Drupal::entityTypeManager()->getStorage('facets_facet');
  $term_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $view_url = Url::fromRoute('view.product_catalog.page_1');
  $view_url = $view_url->toString();

  foreach ($links as &$link) {
    $menu_name = isset($link['menu_name']) ? $link['menu_name'] : '';
    if ($link['provider'] == 'taxonomy_menu' && $menu_name == 'catalog') {
      // Generate the path to the view + facets.
      // Assumes that the facet is named the same as the vocabulary.
      $term = $term_storage->load($link['metadata']['taxonomy_term_id']);
      /** @var \Drupal\facets\FacetInterface $facet */
      $facet = $facet_storage->load($term->bundle());
      $label = $alias_cleaner->cleanString($term->label());

      $link['url'] = 'internal:' . $view_url . '/' . $facet->getUrlAlias() . '/' . $label . '-' . $term->id();
      $link['route_name'] = '';
      $link['route_parameters'] = [];
      $link['load arguments'] = [];
    }
  }
}
