<?php

/**
 * @file
 * Contains matrix_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function matrix_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the matrix_field module.
    case 'help.page.matrix_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Matrix Field.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function matrix_field_theme() {
  return [
    'matrix_field' => [
      'render element' => 'elements',
    ]
  ];
}

/**
 * Preprocesses variables for matrix field template.
 * @param $variables
 */
function template_preprocess_matrix_field(&$variables) {
  $items = [];
  foreach ($variables['elements'] as $key => $value) {
    if ($key === '#groups') {
      $variables['groups'] = $value;
    } elseif (strpos($key, '#') === FALSE) {
      $items[] = $value;
    }
  }
  if ($variables['elements']['#label_display'] !== 'hidden') {
    $variables['label'] = $variables['elements']['#title'];
  }
  $variables['items'] = $items;
}

/**
 * Helper function to sort fields by weights
 * @param $field1
 * @param $field2
 *
 * @return int
 */
function _matrix_field_sort_fields($field1, $field2) {
  $a = $field1->get('weight');
  $b = $field2->get('weight');
  if ($a === $b) {
    return 0;
  }
  return ($a < $b) ? -1 : 1;
}
