<?php

use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @file
 * Multi value field module.
 *
 * This file provide drupal hooks.
 */


/**
 * Implements hook_help().
 *
 * Display help page.
 */
function multivaluefield_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.multivaluefield') {

    $current_url = Url::fromRoute('<current>');
    if (strstr($current_url->toString(), '/admin/help/multivaluefield') === FALSE) {
      return TRUE;
    }

    $output = '';
    $output .= '<h3>About</h3>';
    $output .= '<p>@TODO : About multivaluefield.
</p>';

    return $output;
  }
}

/**
 * Implements hook_theme().
 * Add multivaluefield template.
 */
function multivaluefield_theme($existing, $type, $theme, $path) {
  return array(
    'multivaluefield' => array(
      'variables' => array(
        'header' => NULL,
        'rows' => NULL,
        'attributes' => NULL,
        'settings' => [],
      ),
    ),
  );
}


/**
 * Implements hook_theme_suggestions_HOOK().
 *  Add template suggestions.
 */
function multivaluefield_theme_suggestions_multivaluefield($variables) {

  $suggestions = array();
  $sett = $variables['settings'];

  $suggestions[] = 'multivaluefield__' . $sett['#field_name'];
  $suggestions[] = 'multivaluefield__' . $sett['#entity_type'];
  $suggestions[] = 'multivaluefield__' . $sett['#bundle'];
  $suggestions[] = 'multivaluefield__' . $sett['#field_name'] . '__' . $sett['#entity_type'] . '__' . $sett['#bundle'];

  return $suggestions;

}

