<?php

/**
 * @file
 * Fill form elements with data from GET or POST values.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\prepopulate\Prepopulators\EntityPrepopulator;

/**
 * Implements hook_entity_prepare_form().
 *
 * Prepopulates all entity forms.
 */
function prepopulate_entity_prepare_form(EntityInterface $entity, string $operation, FormStateInterface $form_state) {
  EntityPrepopulator::create(\Drupal::getContainer(), $entity)->prepopulate();
}
