<?php

/**
 * @file
 * Contains dfinance.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dfinance_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dfinance module.
    case 'help.page.dfinance':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dfinance_theme() {
  $theme = [];

  $theme['financial_doc'] = [
    'render element' => 'elements',
    'file' => 'financial_doc.page.inc',
    'template' => 'financial_doc',
  ];
  $theme['financial_doc_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'financial_doc.page.inc',
  ];

  $theme['finance_supplier'] = [
    'render element' => 'elements',
    'file' => 'finance_supplier.page.inc',
    'template' => 'finance_supplier',
  ];

  $theme['financial_account_code'] = [
    'render element' => 'elements',
    'file' => 'financial_account_code.page.inc',
    'template' => 'financial_account_code',
  ];
  $theme['financial_account_code_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'financial_account_code.page.inc',
  ];

  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function dfinance_theme_suggestions_financial_doc(array $variables) {
  $suggestions = [];
  /** @var \Drupal\dfinance\Entity\FinancialDocInterface $entity */
  $entity = $variables['elements']['#financial_doc'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'financial_doc__' . $sanitized_view_mode;
  $suggestions[] = 'financial_doc__' . $entity->bundle();
  $suggestions[] = 'financial_doc__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'financial_doc__' . $entity->id();
  $suggestions[] = 'financial_doc__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function dfinance_theme_suggestions_financial_account_code(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#financial_account_code'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'financial_account_code__' . $sanitized_view_mode;
  $suggestions[] = 'financial_account_code__' . $entity->bundle();
  $suggestions[] = 'financial_account_code__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'financial_account_code__' . $entity->id();
  $suggestions[] = 'financial_account_code__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function dfinance_theme_suggestions_finance_supplier(array $variables) {
  $suggestions = [];
  /** @var \Drupal\dfinance\Entity\SupplierInterface $entity */
  $entity = $variables['elements']['#finance_supplier'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'finance_supplier__' . $sanitized_view_mode;
  $suggestions[] = 'finance_supplier__' . $entity->id();
  $suggestions[] = 'finance_supplier__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function dfinance_entity_bundle_info_alter(&$bundles) {
  // We need to add the bundle description to each Financial Doc Bundle so that it shows on the Financial Doc Add page.
  foreach ($bundles['financial_doc'] as $name => $info) {
    /** @var \Drupal\dfinance\Entity\FinancialDocTypeInterface $financial_doc_type */
    $financial_doc_type = \Drupal::entityTypeManager()->getStorage('financial_doc_type')->load($name);
    $bundles['financial_doc'][$name]['description'] = $financial_doc_type->getDescription();
  }
}
