<?php

/**
 * @file
 * Primary module hooks for Group Behavior Field Sync module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\group_behavior_field_sync\FieldSyncEntityHooks;
use Drupal\group_behavior_field_sync\FieldSyncFormHooks;

/**
 * Implements hook_form_FORM_ID_alter() for group_type_edit_form.
 */
function group_behavior_field_sync_form_group_type_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  FieldSyncFormHooks::alterGroupTypeEditForm($form, $form_state, $form_id);
}

/**
 * Implements hook_entity_insert().
 */
function group_behavior_field_sync_entity_insert(EntityInterface $entity) {
  FieldSyncEntityHooks::postSave($entity);
}

/**
 * Implements hook_entity_update().
 */
function group_behavior_field_sync_entity_update(EntityInterface $entity) {
  FieldSyncEntityHooks::postSave($entity);
}
